* File: inv.pex.spi.INV.pxi
* Created: Mon Oct 30 15:14:36 2023
* 
x_PM_INV_A N_A_MM1_g N_A_MM0_g A PM_INV_A
x_PM_INV_OUT N_OUT_MM0_d N_OUT_MM1_d OUT PM_INV_OUT
x_PM_INV_VSS VSS N_VSS_MM1_b N_VSS_MM1_s PM_INV_VSS
x_PM_INV_VDD N_VDD_MM0_b N_VDD_MM0_s VDD PM_INV_VDD
